# Generated by Django 4.0.1 on 2022-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hre',
            field=models.FloatField(default=0),
        ),
    ]
