# Generated by Django 4.0.1 on 2022-01-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_hre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hre',
        ),
    ]
